<?php
return array (
  'name' => 
  array (
    'fieldid' => '108',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'name',
    'name' => '姓名',
    'tips' => '请填写你的姓名',
    'css' => '.form-control',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'number' => 
  array (
    'fieldid' => '109',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'number',
    'name' => '学号',
    'tips' => '请填写你的学号',
    'css' => 'form-control',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '{"minnumber":"1","maxnumber":"","decimaldigits":"0","size":"","defaultvalue":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'minnumber' => '1',
    'maxnumber' => '',
    'decimaldigits' => '0',
    'size' => '',
    'defaultvalue' => '',
  ),
);
?>